# Setup
title:               Dong IL Lee
tagline:             '- Personal Webpage'
description:         '• Researcher Associate at KAIST<br>• Research interest:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ultra-fast Photonics<br><br>- Daejeon, South Korea<br><a href="mailto:ehddlf94@kaist.ac.kr">- Email</a><br> <a href="https://scholar.google.com/citations?user=FtQgkM8AAAAJ&hl=ko">- Google Scholar</a>'
url:                 "https://LDongIL.github.io"

baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
